apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: project
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vcupp6qt69w=,iv:EPGV5P2jktRBx7m7J+V/BFr1vgI0l/q9KFC3JPNJkNU=,tag:JjjaDwK0cyA80TFK0c7Diw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:Iat8uX0foEVZcxWmJagYuL/5FlDVeEY1R1qD3UjFLghbR1R6z7MklhhVi8sPar41UFBLw4JfZ0ii+0VW12E1cb4FFB0Z8Ps=,iv:MhnxV7ps6TN9BtYUOrq0A08gbJ+cb8q7n5hMZ77ko9w=,tag:FFNyy3HEtKUaUHO5bVFAdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOEVsVS9QYXF3ZnJzWmw5
            L2lXOEhRQ0VqbDltSXpjYkMrbk1Sd0RzUDJzClVFRzB4Z3RLVVN1VmVvMWhsYTMw
            SFN5RWJoaWNsYnpCZWRDaXlCeTlkNGMKLS0tIFFLYXlmRTZLRUk4bi9SQkpuaXFF
            VWxvYUNhY3BKRG9telo0dkpxVjdaTG8KaWqiMfw9/Y3I2S3dqJCbHHJEcO/QjsVH
            vtNUjvJivupgUBLZcxiFL+EfbUnpVXz6HZBftAyeCGx0v4ag1bOH9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c2mqdlakw6dk8w9eqeefmxtxzv84sygy28hjuct8rc98h42efckswtm63t
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T19:50:00Z"
    mac: ENC[AES256_GCM,data:w12985KkED8ld2EN446IRNS7S1i3icYPUY3UrqBSAUNtyGGFiP2DdbyFE6rIPcQ5kAu3uYwXURSwYUKkEDLeKO2/KDi0TXGJ8mpYDIlE0f5QWv9oA/VpqYyrfki5PqAdEFdn6+IbDGsiTRxWLL5JtD43SmYf7qtUIbWASq11RlU=,iv:NGHk46PIDlT359kQZPatHlYy4UK84lev/0deW2Xl3gA=,tag:D94LDxoGBdiNs01g1uyiCg==,type:str]
    version: 3.13.3
