apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: logs
          emptyDir: {}
        - name: log-output-cm-data
          configMap:
            name: log-output-cm
            items:
              - key: "information.txt"
                path: "information.txt"
      containers:
        - name: log-output-writer
          image: daduam/dwk-log-output-writer
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          env:
            - name: OUTPUT_FILE
              value: /app/logs/output.log
        - name: log-output-reader
          image: daduam/dwk-log-output-reader
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: log-output-cm-data
              mountPath: "/config"
              readOnly: true
          env:
            - name: OUTPUT_FILE
              value: /app/logs/output.log
            - name: PORT
              value: "8081"
            - name: PING_PONG_URL
              value: http://ping-pong-svc:3456
            - name: INFORMATION_FILE
              value: "/config/information.txt"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-cm
                  key: message
