apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: logs
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: daduam/dwk-log-output-writer
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          env:
            - name: OUTPUT_FILE
              value: /app/logs/output.log
        - name: log-output-reader
          image: daduam/dwk-log-output-reader
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          env:
            - name: OUTPUT_FILE
              value: /app/logs/output.log
            - name: PORT
              value: "8081"
