apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-todos
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project-todos
  template:
    metadata:
      labels:
        app: the-project-todos
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
      initContainers:
        - name: fix-shared-data-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 65534:65534 /app/data"]
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
      containers:
        - name: the-project-todos
          image: daduam/dwk-the-project-todos
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          env:
            - name: PORT
              value: "8081"
            - name: TODO_API_URL
              value: http://the-project-todos-backend-svc:1234
            - name: PICSUM_URL
              value: https://picsum.photos/1200
            - name: IMAGE_FILE
              value: /app/data/image_file.jpg
            - name: IMAGE_EXPIRY_TIMESTAMP_FILE
              value: /app/data/image_expiry_timestamp_file.txt
